#
# This file contains overrides for the RuboCop (https://github.com/bbatsov/rubocop) Ruby static code analyser.
#
Metrics/BlockLength:
  Max: 45

Metrics/LineLength:
  Max: 300

Metrics/MethodLength:
  Max: 30
