language: python
sudo: required
dist: xenial
python: '3.8'

before_install:
  - ./scripts/load_templates.sh

cache:
  - pip

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - pipenv run pytest tests/unit --cov=app --cov-report xml --ignore=node_modules
  - pipenv run coverage report

after_success:
  - if [ "$BRANCH" != "master" ]; then
      ./scripts/docker_push.sh;
    fi
  - pipenv run codecov

