language: python
sudo: required
dist: trusty
python: '3.6'

before_install:
  - ./scripts/load_templates.sh

cache:
  - pip

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - pipenv run pytest tests/unit --cov=app --cov-report xml --ignore=node_modules
  - pipenv run coverage report

after_success:
  - if [ "$TRAVIS_BRANCH" != "master" ]; then
      ./scripts/docker_push.sh;
    fi
  - pipenv run codecov

branches:
  only:
    - master
