case-webservice:
  host: collect-server
  port: 8171

eq-service:
  host: eq-server
  port: 5000
  public_key: ../keys/sdc-user-authentication-encryption-sr-public-key.pem
  private_key: ../keys/sdc-user-authentication-signing-rrm-private-key.pem
  private_key_passphrase: 'digitaleq'
