version: '3'

services:

  census-rh-ui:
    container_name: census-rh-ui
    build: ./
    depends_on:
      - redis
    environment:
      - REDIS_SERVER=redis
      - REDIS_PORT=6379
      - APP_SETTINGS=DevelopmentConfig
      - PORT=9092
    ports:
      - "9092:9092"

  redis:
    image: redis
    ports:
      - "6379:6379"
